apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qor-example
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
     app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: qor-example
        image: getqor/qor-example
        imagePullPolicy: Always
        ports:
         - containerPort: 7000
        env:
          - name: DBHost
            value: postgres.db.svc.cluster.local
          - name: DBUser
            value: qor
          - name: DBPassword
            value: qor
          - name: WEB_ROOT
            value: /bin
        volumeMounts:
          - name: config-volumes
            mountPath: /bin/config/
      volumes:
        - name: config-volumes
          configMap:
            name: configs
